---
- name: Setup k8s Cluster Environment
  hosts: all
  become: true
  remote_user: "{{ ansible_user }}"
  become_method: sudo
  gather_facts: true
  # ignore_unreachable: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_pipelining: true

  pre_tasks:
    - name: Update & Upgrade PkG's
      apt: update_cache=yes upgrade=yes force_apt_get=true
      # notify: Reboot Docker Setup

    - name: Install Basic PkG's
      apt: name={{ item }} state=latest force_apt_get=true
      loop:
        - [vim, net-tools, zsh, bash-completion, build-essential]
        - [python3-pip, ipvsadm, jq, iputils-ping, network-manager]

    - name: Set vim as default editor
      shell: sudo update-alternatives --set editor $(which vim).basic
      args:
        executable: "{{ ansible_user_shell }}"

    - name: Create /etc/default/locale file
      copy:
        dest: /etc/default/locale
        content: |
          LANG="en_US.UTF-8"
          LC_ALL="en_US.UTF-8"

    - name: Run update-locale
      shell: sudo update-locale

  # roles:
  #   - { role: ./Setup-KubeadmK8s/viasite-ansible.zsh, zsh_user: "{{ ansible_user }}" }

  tasks:
    - import_role: name=./Setup-KubeadmK8s
