---
# --------Post-installation steps for Docker------- #

- name: Install Docker Module for Python (optional)
  pip: name=docker executable=pip3

- name: Create Docker group
  group: name=docker state=present

- name: Add user to Docker group
  user: name={{ ansible_user }} groups=docker append=true

# - name: Switch to Docker group
#   shell: newgrp docker

- name: verify 'normal' docker pull
  docker_container: name=docker image=hello-world state=present

- name: Create & change -R ownership of 'docker' dir!
  file:
    path: /home/{{ ansible_user }}/.docker
    state: directory
    mode: "0775"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true

- name: Start and enable Docker & Containerd
  systemd: name={{ service }} state=started enabled=yes daemon_reload=true
  loop: [docker, containerd]
  loop_control:
    loop_var: service
  notify: Update Unix domain socket Perm!

- name: configure docker log-driver
  copy:
    content: |
      {
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "10m",
        "max-file": "3" 
      },
      "storage-driver": "overlay2"
      }
    dest: /etc/docker/daemon.json
