---
# -------- Docker CNIetup ------- #

- name: Install Containerd CNI-plugin
  get_url:
    url: "{{ containerd_cni_url }}"
    dest: /tmp/cni-plugins.tgz
    force: true

- name: Create /opt/cni/bin directory
  file: path=/opt/cni/bin state=directory

- name: Extract CNI plugins
  unarchive: src=/tmp/cni-plugins.tgz dest=/opt/cni/bin remote_src=yes

- name: comment disabled_plugins line in '/etc/containerd/config.toml'
  command: sudo sed -i 's/^disabled_plugins \=/\#disabled_plugins \=/g' /etc/containerd/config.toml

# containerd config default | sudo tee /etc/containerd/config.toml
# sudo rm -rf /etc/containerd/config.toml

- name: Update Containerd default config.
  lineinfile:
    path: /etc/containerd/config.toml
    line: "{{ cd_config }}"
  loop: "{{ containerd_config_toml }}"
  notify: Restart Docker & Containerd
  loop_control:
    loop_var: cd_config

- name: Check dockerd process
  command: sudo netstat -lntp | grep dockerd

- name: Check dockerd process
  command: netstat -lntp | grep dockerd
  register: dockerd_process
  changed_when: false

- name: Display dockerd process if found
  debug:
    var: dockerd_process.stdout_lines
  when: dockerd_process.stdout_lines | length > 0
  notify: Reboot Docker Setup
